[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
types = { path = "../types" }
